### ISSUE TITLE
document usage with docker and docker-compose plugins

### ISSUE THREAD

**Issue by joemiller** [buildkite-plugins/gcp-workload-identity-federation-buildkite-plugin#6]
In order to get both the `credentials.json` and `token.json` file into the runtime context when using `docker-compose` you need to do something like this in the compose plugin config:

```yaml
          expand-volume-vars: true
          volumes:
            - \$BUILDKITE_OIDC_TMPDIR:/\$BUILDKITE_OIDC_TMPDIR
```
Also need to make sure `GOOGLE_APPLICATION_CREDENTIALS` (or `CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE` if using `gcloud` cli) is being passed into compose either in the compose yaml or the docker-compose plugin config.

It might be a good idea to document this. It took me a bit of trial and error to get it right.

Also document usage with the `docker` plugin.

I have also considered adding a new var to the plugin `path:` that you could use to set a specific path you wanted the files to be placed into. I'm not sure if that's necessary or desired though. One thing I would want to be careful with is the `pre-exit` which does an `rm -rf` on the TMPDIR.  (I'm happy to send a PR for this if it's desired)

If there is a better or simpler way to use this plugin with docker and docker-compose plugins I would love to hear it. thank you

**Comment by joemiller** [comment]
using `docker` plugin:

```yaml
      - docker#v5.9.0:
          image: <IMAGE>
          expand-volume-vars: true
          volumes:
            - \$BUILDKITE_OIDC_TMPDIR:/\$BUILDKITE_OIDC_TMPDIR
          environment:
            - BUILDKITE_OIDC_TMPDIR
            - CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE  # if using 'gcloud'
            - GOOGLE_APPLICATION_CREDENTIALS          # if using literally any other gcp lib
```
